# setting working directory paths
hytale.server.kind=release
# EDIT WITH YOUR PATH TO YOUR INSTALL
# (default Windows path is the same -- but change user folder name to match)
hytale.server.dir=C:\\Users\\Trinity\\AppData\\Roaming\\Hytale\\install\\${hytale.server.kind}\\package\\game\\latest
hytale.plugins.dir=${hytale.server.dir}\\Server\\mods